const express = require('express');
const app = express();
const cookieParser = require('cookie-parser');
app.use(express.json());
app.use(cookieParser());
const productRoute = require('./routes/productRoute');
const userRoutes = require('./routes/userRoutes');
app.use('/api/v1', productRoute);
app.use('/api/v1', userRoutes);
module.exports = app;